# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 347)
        Dialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("*{\n"
"border: none;\n"
"}\n"
"\n"
"#widget{\n"
"background-color: rgb(29, 35, 50)\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"background-color: rgb(227, 227, 227);\n"
"width: 150px;\n"
"height: 50px;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px; \n"
"font: 63 18pt \"Bahnschrift SemiBold Condensed\";\n"
"margin-right: 5px\n"
"}\n"
"\n"
"#tab{\n"
"background-color: rgb(227, 227, 227)\n"
"}\n"
"\n"
"#enregistrerButton{\n"
"background-color: rgb(30, 255, 30);\n"
"}\n"
"\n"
"#annulerButton{\n"
"background-color : rgb(255, 29, 29)\n"
"}\n"
"\n"
"#enregistrerButton, #annulerButton{\n"
"color: white;\n"
"padding: 8px;\n"
"}\n"
"\n"
"#listWidget{\n"
"border: 1px solid black;\n"
"background-color: white;\n"
"color: rgb(29, 35, 50);\n"
"border-radius: 5px\n"
"}\n"
"\n"
"#addCategoryButton, #removeCategoryButton{\n"
"background-color: rgb(231, 231, 231);\n"
"padding: 5px;\n"
"border: 1px solid rgb(29, 35, 50);\n"
"border-radius: 5px\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("")
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addCategoryButton = QtWidgets.QPushButton(self.widget_3)
        self.addCategoryButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addCategoryButton.setIcon(icon)
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.horizontalLayout.addWidget(self.addCategoryButton)
        self.removeCategoryButton = QtWidgets.QPushButton(self.widget_3)
        self.removeCategoryButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/minus-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeCategoryButton.setIcon(icon1)
        self.removeCategoryButton.setObjectName("removeCategoryButton")
        self.horizontalLayout.addWidget(self.removeCategoryButton)
        self.horizontalLayout_3.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enregistrerButton = QtWidgets.QPushButton(self.widget_4)
        self.enregistrerButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enregistrerButton.setFont(font)
        self.enregistrerButton.setObjectName("enregistrerButton")
        self.horizontalLayout_2.addWidget(self.enregistrerButton)
        self.annulerButton = QtWidgets.QPushButton(self.widget_4)
        self.annulerButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.annulerButton.setFont(font)
        self.annulerButton.setObjectName("annulerButton")
        self.horizontalLayout_2.addWidget(self.annulerButton)
        self.horizontalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "Braclets"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Rings"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "Ear Rings"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.enregistrerButton.setText(_translate("Dialog", "Enregistrer"))
        self.annulerButton.setText(_translate("Dialog", "Annuler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Categories"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
