# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles/freemium_over.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 410)
        Dialog.setMinimumSize(QtCore.QSize(700, 410))
        Dialog.setMaximumSize(QtCore.QSize(700, 410))
        Dialog.setStyleSheet("QLabel{\n"
"background-color:none;\n"
"}\n"
"QDialog{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.489, stop:0 rgba(36, 80, 145, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 60, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: red;\n"
"font: 22pt \"Franklin Gothic Medium\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 621, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 250, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(390, 340, 68, 50))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 340, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Votre essai gratuit est terminé ! "))
        self.label_2.setText(_translate("Dialog", "Contactez-moi si vous souhaitez acheter un plan à vie via le numéro de téléphone ci-dessous ou via Facebook."))
        self.label_3.setText(_translate("Dialog", "Numero de tel : 26 997 767"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://www.facebook.com/moadh.oueslati.5/\"><img src=\":/newPrefix/images/icons/facebook.png\" width=\"50\" height=\"50\"/></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Facebook :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
