# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 920)
        MainWindow.setMinimumSize(QtCore.QSize(1290, 920))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border: none;\n"
"}\n"
"\n"
"QLabel{\n"
"color : rgb(29, 35, 50)\n"
"}\n"
"\n"
"#centralwidget, #tab_1{\n"
"background-color: rgb(29, 35, 50)\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"background-color: rgb(161, 161, 161);\n"
"width: 150px;\n"
"height: 50px;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px; \n"
"font: 63 18pt \"Bahnschrift SemiBold Condensed\";\n"
"margin-right: 5px\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(227, 227, 227);\n"
"}\n"
"\n"
"/* Product Informations Container (Right Side) */\n"
"#ProductInfoWidget{\n"
"background-color: rgb(227, 227, 227)\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QPushButton{\n"
"padding: 5px;\n"
"border: 1px solid rgb(29, 35, 50);\n"
"border-radius: 5px\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"border: 1px solid rgb(29, 35, 50);\n"
"background-color: lightgray;\n"
"border-radius: 5px\n"
"}\n"
"\n"
"#ajouterCategorieButton{\n"
"background-color: rgb(29, 35, 50);\n"
"color: white\n"
"}\n"
"\n"
"#ajouterCategorieButton:hover{\n"
"background-color: black;\n"
"}\n"
"\n"
"/* Product image Container (Left Side) */\n"
"#ProductImageWidget{\n"
"background-color : rgb(227, 227, 227)\n"
"}\n"
"\n"
"#productPictureLabel{\n"
"border: 2px dashed rrgb(29, 35, 50);\n"
"}\n"
"\n"
"#ajouterImageButton{\n"
"background-color: rgb(203, 203, 203)\n"
"}\n"
"\n"
"#ajouterImageButton:hover{\n"
"background-color: rgb(190, 190, 190)\n"
"}\n"
"\n"
"/* Table Container */\n"
"#tableOuterWidget{\n"
"background-color: rgb(227, 227, 227)\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section:selected {\n"
"background-color: #4CAF50;  /* Selected header background color */\n"
"color: red;  /* Selected header text color */\n"
"font-weight: normal;  /* Prevent bold font on selected state */\n"
"}\n"
"\n"
"\n"
"/* Bottom Containers (Buttons) */\n"
"#nouveauButton, #enregistrerButton, #precedentButton, #suivantButton, #modifierButton, #annulerButton, #supprimerButton{\n"
"padding: 10px;\n"
"color: rgb(29, 35, 50);\n"
"}\n"
"\n"
"#bottomContainer{\n"
"background-color: rgb(227, 227, 227)\n"
"}\n"
"\n"
"\n"
"/* Second Tab */\n"
"#tab_2{\n"
" background-color:  rgb(227, 227, 227);\n"
"}\n"
"\n"
"/* Third Tab */\n"
"#tab_3{\n"
" background-color:  rgb(227, 227, 227);\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(11, 20, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.tab_1)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ProductImageWidget = QtWidgets.QWidget(self.widget)
        self.ProductImageWidget.setMinimumSize(QtCore.QSize(345, 0))
        self.ProductImageWidget.setObjectName("ProductImageWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ProductImageWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.ProductImageWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.widget_4 = QtWidgets.QWidget(self.ProductImageWidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ajouterImageButton = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ajouterImageButton.setFont(font)
        self.ajouterImageButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ajouterImageButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ajouterImageButton.setIcon(icon)
        self.ajouterImageButton.setIconSize(QtCore.QSize(30, 30))
        self.ajouterImageButton.setObjectName("ajouterImageButton")
        self.verticalLayout_4.addWidget(self.ajouterImageButton)
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.productPictureLabel = QtWidgets.QLabel(self.widget_9)
        self.productPictureLabel.setMaximumSize(QtCore.QSize(280, 270))
        self.productPictureLabel.setText("")
        self.productPictureLabel.setScaledContents(True)
        self.productPictureLabel.setObjectName("productPictureLabel")
        self.horizontalLayout_4.addWidget(self.productPictureLabel)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.ProductImageWidget)
        self.widget_2.setStyleSheet("QPushButton{\n"
"font: 14pt \"Stencil\";\n"
"border-radius: 10px;\n"
"color: white\n"
"}\n"
"\n"
"#acheteeButton{\n"
"border: 3px solid rgb(9, 185, 0);\n"
"background-color: rgb(40, 209, 54)\n"
"}\n"
"\n"
"#vendueButton{\n"
"border: 3px solid red;\n"
"background-color: rgb(255, 58, 58);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acheteeButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.acheteeButton.setFont(font)
        self.acheteeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acheteeButton.setStyleSheet("")
        self.acheteeButton.setObjectName("acheteeButton")
        self.horizontalLayout_3.addWidget(self.acheteeButton)
        self.vendueButton = QtWidgets.QPushButton(self.widget_2)
        self.vendueButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vendueButton.setObjectName("vendueButton")
        self.horizontalLayout_3.addWidget(self.vendueButton)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 6)
        self.horizontalLayout.addWidget(self.ProductImageWidget)
        self.ProductInfoWidget = QtWidgets.QWidget(self.widget)
        self.ProductInfoWidget.setObjectName("ProductInfoWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.ProductInfoWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.nomProduitLineEdit = QtWidgets.QLineEdit(self.ProductInfoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nomProduitLineEdit.sizePolicy().hasHeightForWidth())
        self.nomProduitLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nomProduitLineEdit.setFont(font)
        self.nomProduitLineEdit.setAutoFillBackground(False)
        self.nomProduitLineEdit.setStyleSheet("background-color: lightgray;\n"
"")
        self.nomProduitLineEdit.setText("")
        self.nomProduitLineEdit.setFrame(True)
        self.nomProduitLineEdit.setObjectName("nomProduitLineEdit")
        self.gridLayout.addWidget(self.nomProduitLineEdit, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dateEntreeLineEdit = QtWidgets.QLineEdit(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEntreeLineEdit.setFont(font)
        self.dateEntreeLineEdit.setStyleSheet("background-color: lightgray;\n"
"color: rgb(60, 60, 60)")
        self.dateEntreeLineEdit.setReadOnly(True)
        self.dateEntreeLineEdit.setObjectName("dateEntreeLineEdit")
        self.gridLayout.addWidget(self.dateEntreeLineEdit, 4, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 3, 1, 1)
        self.categorieComboBox = QtWidgets.QComboBox(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.categorieComboBox.setFont(font)
        self.categorieComboBox.setStyleSheet("background-color: lightgray;\n"
"")
        self.categorieComboBox.setObjectName("categorieComboBox")
        self.categorieComboBox.addItem("")
        self.gridLayout.addWidget(self.categorieComboBox, 2, 2, 1, 1)
        self.rechercherCategorieComboBox = QtWidgets.QComboBox(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rechercherCategorieComboBox.setFont(font)
        self.rechercherCategorieComboBox.setStyleSheet("background-color: lightgray;\n"
"")
        self.rechercherCategorieComboBox.setFrame(True)
        self.rechercherCategorieComboBox.setObjectName("rechercherCategorieComboBox")
        self.rechercherCategorieComboBox.addItem("")
        self.gridLayout.addWidget(self.rechercherCategorieComboBox, 0, 2, 1, 2)
        self.quantiteVendueTotaleLineEdit = QtWidgets.QLineEdit(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantiteVendueTotaleLineEdit.setFont(font)
        self.quantiteVendueTotaleLineEdit.setStyleSheet("background-color: lightgray;\n"
"")
        self.quantiteVendueTotaleLineEdit.setReadOnly(False)
        self.quantiteVendueTotaleLineEdit.setObjectName("quantiteVendueTotaleLineEdit")
        self.gridLayout.addWidget(self.quantiteVendueTotaleLineEdit, 3, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.prixAchatSpinBox = QtWidgets.QDoubleSpinBox(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prixAchatSpinBox.setFont(font)
        self.prixAchatSpinBox.setStyleSheet("background-color: lightgray;\n"
"")
        self.prixAchatSpinBox.setDecimals(1)
        self.prixAchatSpinBox.setMaximum(999999.0)
        self.prixAchatSpinBox.setObjectName("prixAchatSpinBox")
        self.gridLayout.addWidget(self.prixAchatSpinBox, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.prixVenteSpinBox = QtWidgets.QDoubleSpinBox(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prixVenteSpinBox.setFont(font)
        self.prixVenteSpinBox.setStyleSheet("background-color: lightgray;\n"
"")
        self.prixVenteSpinBox.setDecimals(1)
        self.prixVenteSpinBox.setMaximum(999999.0)
        self.prixVenteSpinBox.setObjectName("prixVenteSpinBox")
        self.gridLayout.addWidget(self.prixVenteSpinBox, 4, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.ProductInfoWidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 2, 1, 3)
        self.ajouterCategorieButton = QtWidgets.QPushButton(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ajouterCategorieButton.setFont(font)
        self.ajouterCategorieButton.setStyleSheet("")
        self.ajouterCategorieButton.setObjectName("ajouterCategorieButton")
        self.gridLayout.addWidget(self.ajouterCategorieButton, 0, 4, 1, 1)
        self.quantiteActuelleLineEdit = QtWidgets.QLineEdit(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantiteActuelleLineEdit.setFont(font)
        self.quantiteActuelleLineEdit.setStyleSheet("background-color: lightgray;\n"
"")
        self.quantiteActuelleLineEdit.setReadOnly(False)
        self.quantiteActuelleLineEdit.setObjectName("quantiteActuelleLineEdit")
        self.gridLayout.addWidget(self.quantiteActuelleLineEdit, 1, 4, 1, 1)
        self.quantiteAchatTotaleLineEdit = QtWidgets.QLineEdit(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantiteAchatTotaleLineEdit.setFont(font)
        self.quantiteAchatTotaleLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.quantiteAchatTotaleLineEdit.setStyleSheet("background-color: lightgray;\n"
"")
        self.quantiteAchatTotaleLineEdit.setReadOnly(False)
        self.quantiteAchatTotaleLineEdit.setObjectName("quantiteAchatTotaleLineEdit")
        self.gridLayout.addWidget(self.quantiteAchatTotaleLineEdit, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ProductInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.dateEntreeLineEdit.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_4.raise_()
        self.nomProduitLineEdit.raise_()
        self.label_3.raise_()
        self.label_12.raise_()
        self.categorieComboBox.raise_()
        self.rechercherCategorieComboBox.raise_()
        self.quantiteVendueTotaleLineEdit.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.prixAchatSpinBox.raise_()
        self.prixVenteSpinBox.raise_()
        self.plainTextEdit.raise_()
        self.ajouterCategorieButton.raise_()
        self.quantiteActuelleLineEdit.raise_()
        self.quantiteAchatTotaleLineEdit.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.horizontalLayout.addWidget(self.ProductInfoWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_5.addWidget(self.widget)
        self.tableOuterWidget = QtWidgets.QWidget(self.tab_1)
        self.tableOuterWidget.setStyleSheet("")
        self.tableOuterWidget.setObjectName("tableOuterWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tableOuterWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tableOuterWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"background-color :  rgb(29, 35, 50) ;\n"
"border:1px solid white;\n"
"font-size: 18px;\n"
"color:white;\n"
"padding: 2px\n"
"}\n"
"QTableWidget::item:selected {\n"
"background-color: rgb(29, 35, 50) ;\n"
"color: white;\n"
"}\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.tableOuterWidget)
        self.bottomContainer = QtWidgets.QWidget(self.tab_1)
        self.bottomContainer.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bottomContainer.setObjectName("bottomContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottomContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nouveauButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nouveauButton.setFont(font)
        self.nouveauButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nouveauButton.setIcon(icon1)
        self.nouveauButton.setIconSize(QtCore.QSize(25, 25))
        self.nouveauButton.setObjectName("nouveauButton")
        self.horizontalLayout_2.addWidget(self.nouveauButton)
        self.enregistrerButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enregistrerButton.setFont(font)
        self.enregistrerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enregistrerButton.setIcon(icon2)
        self.enregistrerButton.setIconSize(QtCore.QSize(30, 30))
        self.enregistrerButton.setObjectName("enregistrerButton")
        self.horizontalLayout_2.addWidget(self.enregistrerButton)
        self.precedentButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.precedentButton.setFont(font)
        self.precedentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.precedentButton.setIcon(icon3)
        self.precedentButton.setIconSize(QtCore.QSize(25, 25))
        self.precedentButton.setObjectName("precedentButton")
        self.horizontalLayout_2.addWidget(self.precedentButton)
        self.suivantButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.suivantButton.setFont(font)
        self.suivantButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suivantButton.setIcon(icon4)
        self.suivantButton.setIconSize(QtCore.QSize(25, 25))
        self.suivantButton.setObjectName("suivantButton")
        self.horizontalLayout_2.addWidget(self.suivantButton)
        self.modifierButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.modifierButton.setFont(font)
        self.modifierButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/editing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modifierButton.setIcon(icon5)
        self.modifierButton.setIconSize(QtCore.QSize(30, 30))
        self.modifierButton.setObjectName("modifierButton")
        self.horizontalLayout_2.addWidget(self.modifierButton)
        self.annulerButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.annulerButton.setFont(font)
        self.annulerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.annulerButton.setIcon(icon6)
        self.annulerButton.setIconSize(QtCore.QSize(25, 25))
        self.annulerButton.setObjectName("annulerButton")
        self.horizontalLayout_2.addWidget(self.annulerButton)
        self.supprimerButton = QtWidgets.QPushButton(self.bottomContainer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.supprimerButton.setFont(font)
        self.supprimerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/pictures/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.supprimerButton.setIcon(icon7)
        self.supprimerButton.setIconSize(QtCore.QSize(30, 30))
        self.supprimerButton.setObjectName("supprimerButton")
        self.horizontalLayout_2.addWidget(self.supprimerButton)
        self.verticalLayout_5.addWidget(self.bottomContainer)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.achatTableWidget = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.achatTableWidget.setFont(font)
        self.achatTableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.achatTableWidget.setStyleSheet("QHeaderView::section {\n"
"background-color :  rgb(29, 35, 50) ;\n"
"border:1px solid white;\n"
"font-size: 18px;\n"
"color:white;\n"
"padding: 2px\n"
"}\n"
"QTableWidget::item:selected {\n"
"background-color: rgb(98, 210, 243);\n"
"color: black;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"background-color: rgb(190, 190, 190)\n"
"}")
        self.achatTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.achatTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.achatTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.achatTableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.achatTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.achatTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.achatTableWidget.setShowGrid(True)
        self.achatTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.achatTableWidget.setWordWrap(True)
        self.achatTableWidget.setCornerButtonEnabled(False)
        self.achatTableWidget.setObjectName("achatTableWidget")
        self.achatTableWidget.setColumnCount(7)
        self.achatTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.achatTableWidget.setItem(0, 0, item)
        self.achatTableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.achatTableWidget.horizontalHeader().setHighlightSections(False)
        self.achatTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.achatTableWidget.horizontalHeader().setStretchLastSection(False)
        self.achatTableWidget.verticalHeader().setVisible(False)
        self.achatTableWidget.verticalHeader().setHighlightSections(False)
        self.achatTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.achatTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.achatTableWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.venteTableWidget = QtWidgets.QTableWidget(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.venteTableWidget.setFont(font)
        self.venteTableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.venteTableWidget.setStyleSheet("QHeaderView::section {\n"
"background-color :  rgb(29, 35, 50) ;\n"
"border:1px solid white;\n"
"font-size: 18px;\n"
"color:white;\n"
"padding: 2px\n"
"}\n"
"QTableWidget::item:selected {\n"
"background-color: rgb(98, 210, 243);\n"
"color: black;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"background-color: rgb(190, 190, 190)\n"
"}\n"
"")
        self.venteTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.venteTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.venteTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.venteTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.venteTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.venteTableWidget.setShowGrid(True)
        self.venteTableWidget.setWordWrap(True)
        self.venteTableWidget.setCornerButtonEnabled(False)
        self.venteTableWidget.setObjectName("venteTableWidget")
        self.venteTableWidget.setColumnCount(7)
        self.venteTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.venteTableWidget.setHorizontalHeaderItem(6, item)
        self.venteTableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.venteTableWidget.horizontalHeader().setHighlightSections(False)
        self.venteTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.venteTableWidget.horizontalHeader().setStretchLastSection(False)
        self.venteTableWidget.verticalHeader().setVisible(False)
        self.venteTableWidget.verticalHeader().setHighlightSections(False)
        self.venteTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.venteTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.venteTableWidget)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StockUp"))
        self.label_2.setText(_translate("MainWindow", "Image du Produit"))
        self.ajouterImageButton.setText(_translate("MainWindow", " Ajouter Image"))
        self.acheteeButton.setText(_translate("MainWindow", "achetée"))
        self.vendueButton.setText(_translate("MainWindow", "vendue"))
        self.label_11.setText(_translate("MainWindow", "Notes :"))
        self.label_12.setText(_translate("MainWindow", "Rechercher Catégorie :"))
        self.label_4.setText(_translate("MainWindow", "Catégorie :"))
        self.label_3.setText(_translate("MainWindow", "Nom du Produit :"))
        self.dateEntreeLineEdit.setText(_translate("MainWindow", "--/--/----"))
        self.label_10.setText(_translate("MainWindow", "     Date d\'Entrée :"))
        self.label_9.setText(_translate("MainWindow", "     Quantité Vendue :"))
        self.categorieComboBox.setItemText(0, _translate("MainWindow", "Non catégorisé"))
        self.rechercherCategorieComboBox.setCurrentText(_translate("MainWindow", "----------TOUT----------"))
        self.rechercherCategorieComboBox.setItemText(0, _translate("MainWindow", "----------TOUT----------"))
        self.quantiteVendueTotaleLineEdit.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Prix d\'Achat (dt) :"))
        self.label_5.setText(_translate("MainWindow", "Prix de Vente (dt) :"))
        self.ajouterCategorieButton.setText(_translate("MainWindow", "Ajouter Categorie"))
        self.quantiteActuelleLineEdit.setText(_translate("MainWindow", "0"))
        self.quantiteAchatTotaleLineEdit.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "     Quantité Achetée :"))
        self.label_8.setText(_translate("MainWindow", "     Quantité Actuelle:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom du Produit"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantité Actuelle"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Qte Achetée Totale"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Qte Vendue Totale"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total Dépensé (dt)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Gagné (dt)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bénéfices (dt)"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Catégorie"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Date d\'Entrée"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Notes"))
        self.nouveauButton.setText(_translate("MainWindow", " NOUVEAU"))
        self.enregistrerButton.setText(_translate("MainWindow", "ENREGISTRER"))
        self.precedentButton.setText(_translate("MainWindow", "PRÉCÉDENT"))
        self.suivantButton.setText(_translate("MainWindow", "SUIVANT"))
        self.modifierButton.setText(_translate("MainWindow", "MODIFIER"))
        self.annulerButton.setText(_translate("MainWindow", "ANNULER"))
        self.supprimerButton.setText(_translate("MainWindow", "SUPPRIMER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Produits"))
        self.achatTableWidget.setSortingEnabled(False)
        item = self.achatTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.achatTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom du Produit"))
        item = self.achatTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantité Achetée"))
        item = self.achatTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prix d\'Achat (dt)"))
        item = self.achatTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fournisseurs"))
        item = self.achatTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Catégorie"))
        item = self.achatTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date d\'Entrée"))
        item = self.achatTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Notes"))
        __sortingEnabled = self.achatTableWidget.isSortingEnabled()
        self.achatTableWidget.setSortingEnabled(False)
        item = self.achatTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "honey"))
        self.achatTableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Achats"))
        self.venteTableWidget.setSortingEnabled(False)
        item = self.venteTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom du Produit"))
        item = self.venteTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantité Vendue"))
        item = self.venteTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prix de Vente (dt)"))
        item = self.venteTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nom du Client"))
        item = self.venteTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Catégorie"))
        item = self.venteTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date d\'Entrée"))
        item = self.venteTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Notes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Ventes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
